version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: drupal/core-project-message
    versions:
    - 9.1.3
    - 9.1.4
    - 9.1.5
    - 9.1.6
  - dependency-name: drupal/core-composer-scaffold
    versions:
    - 9.1.3
    - 9.1.4
    - 9.1.5
    - 9.1.6
  - dependency-name: drush/drush
    versions:
    - 10.3.6
    - 10.4.0
    - 10.4.1
    - 10.4.2
  - dependency-name: drupal/bootstrap4
    versions:
    - 2.1.4
    - 2.1.5
    - 2.1.6
  - dependency-name: drupal/ds
    versions:
    - 3.10.0
    - 3.11.0
    - 3.9.0
  - dependency-name: drupal/core-recommended
    versions:
    - 8.9.13
  - dependency-name: drupal/core-dev
    versions:
    - 8.9.13
  - dependency-name: composer/installers
    versions:
    - 1.10.0
  - dependency-name: drupal/inline_entity_form
    versions:
    - 1.0.0-rc8
